---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-postgresql
  namespace: staging
  labels:
    app: keycloak-postgresql
spec:
  containers:
    - name: postgresql
      image: postgres:latest
      volumeMounts:
      - mountPath: "/var/lib/postgresql"
        name: keycloak-postgresql-volume
      env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rlgl-secrets
            key: keycloak-postgresql-password
      - name: POSTGRES_USER
        value: "keycloak"
      - name: POSTGRES_DB
        value: "keycloak"
  initContainers:
  - name: pgsql-data-permission-fix
    image: busybox
    command: ["/bin/chmod","-R","777", "/data"]
    volumeMounts:
    - name: keycloak-postgresql-volume
      mountPath: /data
  volumes:
    - name: keycloak-postgresql-volume
      persistentVolumeClaim:
        claimName: keycloak-postgresql-pvc3
