---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  namespace: staging
  labels:
    app: keycloak
spec:
  containers:
    - name: keycloak
      image: jboss/keycloak:latest
      livenessProbe:
        httpGet:
          path: /auth/realms/master
          port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
      env:
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_USER
        value: "admin"
      - name: KEYCLOAK_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rlgl-secrets
            key: keycloak-admin-password
      - name: DB_VENDOR
        value: "postgres"
      - name: DB_ADDR
        value: "keycloak-postgresql"
      - name: DB_USER
        value: "keycloak"
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rlgl-secrets
            key: keycloak-postgresql-password

