---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  namespace: staging
  labels:
    app: keycloak
spec:
  containers:
    - name: keycloak
      image: moxielogic/rlgl-server-keycloak:latest
      env:
      - name: KEYCLOAK_USER
        value: "admin"
      - name: KEYCLOAK_PASSWORD
        value: "open"
      volumeMounts:
      - name: rlgl-server-realm
        mountPath: "/opt/jboss/keycloak/rlgl"
        readOnly: true
  volumes:
  - name: rlgl-server-realm
    secret:
      secretName: rlgl-server-realm
