---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rlgl-pvc2
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

