---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rlgl-server
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rlgl-server
    spec:
      containers:
      - name: rlgl-server
        image: moxielogic/rlgl-server:v1.0.0-141-gd83ad56
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 9101
          protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/rlgl
          name: rlgl-server-config
        env:
        - name: KEYLOAK_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: rlgl-secrets
              key: keycloak-oidc-client-secret
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rlgl-secrets
              key: rlgl-postgresql-password
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rlgl-secrets
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rlgl-secrets
              key: AWS_SECRET_KEY
      volumes:
      - name: rlgl-server-config
        configMap:
          name: rlgl-server-config
          items:
          - key: config.ini
            path: config.ini
