apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-rlgl-server
  namespace: default
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  spec:
  rules:
  - host: rl.gl
    http:
      paths:
      - path: /
        backend:
          serviceName: rlgl-server
          servicePort: 80
