---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rlgl-pvc3
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

